#!/bin/sh
### BEGIN INIT INFO
# Provides           lgc-rabbit
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: docker rabbit mq
# Description:       Init script for the docker rabbit mq
### END INIT INFO
#
# Author:   "lordgasmic" <lordgasmic@lordgasmic.com>
#
set -e

PATH=/bin:/usr/bin:/sbin:/usr/sbin

case "$1" in
  start)
    docker start rabbitmq
    ;;
  stop)
    docker stop rabbitmq
    ;;
  status)
    docker ps -f name=rabbitmq
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: /etc/init.d/lgc-rabbit {start|stop|restart|force-reload}"
    exit 1
    ;;
esac

exit 0
